# Task 1

In [2]:
import numpy as np
# 1D array from 1 to 10
arr1 = np.arange(1, 11)
# 3x3 2D array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# 4x4 zeros array
zeros_arr = np.zeros((4, 4))
# 2x5 ones array
ones_arr = np.ones((2, 5))
print("1D Array:")
print(arr1)
print("\n2D Array:")
print(arr2)
print("\nZeros Array:")
print(zeros_arr)
print("\nOnes Array:")
print(ones_arr)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Task 2

In [3]:
print("Shape:", arr2.shape)
print("Total Elements:", arr2.size)
print("Data Type:", arr2.dtype)
print("Dimensions:", arr2.ndim)
print("\nWhy shape is important in AI?")
print("Shape tells rows and columns of data.")
print("AI models need correct input dimensions for training.")

Shape: (3, 3)
Total Elements: 9
Data Type: int64
Dimensions: 2

Why shape is important in AI?
Shape tells rows and columns of data.
AI models need correct input dimensions for training.


# Task 3

In [4]:
arr3 = np.array([10, 20, 30, 40, 50, 60])
print("Array:", arr3)
print("First Element:", arr3[0])
print("Last Element:", arr3[-1])
print("Third Element:", arr3[2])
print("Values Greater Than 30:")
print(arr3[arr3 > 30])

Array: [10 20 30 40 50 60]
First Element: 10
Last Element: 60
Third Element: 30
Values Greater Than 30:
[40 50 60]


# Task 4

In [5]:
print("Elements from index 1 to 4:")
print(arr3[1:5])
print("Reversed Array:")
print(arr3[::-1])
print("Alternate Elements:")
print(arr3[::2])
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\nMatrix:")
print(matrix)
print("First Row:")
print(matrix[0])
print("Second Column:")
print(matrix[:, 1])
print("Last Two Rows:")
print(matrix[1:])

Elements from index 1 to 4:
[20 30 40 50]
Reversed Array:
[60 50 40 30 20 10]
Alternate Elements:
[10 30 50]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
First Row:
[1 2 3]
Second Column:
[2 5 8]
Last Two Rows:
[[4 5 6]
 [7 8 9]]


# Task 5

In [6]:
vec_arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", vec_arr)
print("Multiply by 5:")
print(vec_arr * 5)
print("Add 10:")
print(vec_arr + 10)
print("Square Elements:")
print(vec_arr ** 2)
print("\nWhy vectorization is important in AI?")
print("Vectorization makes computations faster and efficient.")
print("It avoids loops and improves AI model performance.")

Original Array: [1 2 3 4 5]
Multiply by 5:
[ 5 10 15 20 25]
Add 10:
[11 12 13 14 15]
Square Elements:
[ 1  4  9 16 25]

Why vectorization is important in AI?
Vectorization makes computations faster and efficient.
It avoids loops and improves AI model performance.


# Task 6

In [7]:
b_arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original Array:")
print(b_arr)
print("Add 10 using broadcasting:")
print(b_arr + 10)
print("Multiply by 2:")
print(b_arr * 2)
print("\nBroadcasting helps machine learning by")
print("performing operations on large datasets efficiently.")

Original Array:
[[1 2 3]
 [4 5 6]]
Add 10 using broadcasting:
[[11 12 13]
 [14 15 16]]
Multiply by 2:
[[ 2  4  6]
 [ 8 10 12]]

Broadcasting helps machine learning by
performing operations on large datasets efficiently.


# Task 7

In [8]:
mat1 = np.array([
    [1, 2],
    [3, 4]
])
mat2 = np.array([
    [5, 6],
    [7, 8]
])
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print("Addition:")
print(mat1 + mat2)
print("Subtraction:")
print(mat1 - mat2)

Matrix 1:
[[1 2]
 [3 4]]
Matrix 2:
[[5 6]
 [7 8]]
Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]


# Task 8

In [9]:
m1 = np.array([
    [1, 2],
    [3, 4]
])
m2 = np.array([
    [5, 6],
    [7, 8]
])
print("Matrix Multiplication:")
print(np.dot(m1, m2))
print("Transpose of Matrix 1:")
print(m1.T)
print("\nMatrix multiplication is used in neural networks")
print("for calculations between inputs, weights, and outputs.")

Matrix Multiplication:
[[19 22]
 [43 50]]
Transpose of Matrix 1:
[[1 3]
 [2 4]]

Matrix multiplication is used in neural networks
for calculations between inputs, weights, and outputs.


# Task 9

In [10]:
rand_int = np.random.randint(1, 101, (4, 4))
print("Random Integer Array:")
print(rand_int)
rand_decimal = np.random.rand(4, 4)
print("\nRandom Decimal Array:")
print(rand_decimal)
print("\nMaximum Value:", np.max(rand_int))
print("Minimum Value:", np.min(rand_int))
print("Average Value:", np.mean(rand_int))
print("\nRandom numbers are important in AI")
print("for training, testing, and initializing models.")

Random Integer Array:
[[  2  75  37  60]
 [ 27  20  15  16]
 [ 96  70 100  25]
 [ 92  68  73  21]]

Random Decimal Array:
[[0.37958191 0.50626939 0.37974861 0.04223419]
 [0.64733792 0.16261427 0.02190981 0.781491  ]
 [0.52122089 0.02305924 0.81779807 0.07388197]
 [0.03433699 0.30495345 0.539531   0.39636464]]

Maximum Value: 100
Minimum Value: 2
Average Value: 49.8125

Random numbers are important in AI
for training, testing, and initializing models.


# Task 10

In [11]:
marks = np.array([85, 72, 90, 45, 66, 39, 81, 95, 50, 77])
print("Marks:", marks)
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Students Scoring Above 80:")
print(np.sum(marks > 80))
print("Failed Students (Below 50):")
print(marks[marks < 50])

Marks: [85 72 90 45 66 39 81 95 50 77]
Average Marks: 70.0
Highest Marks: 95
Lowest Marks: 39
Students Scoring Above 80:
4
Failed Students (Below 50):
[45 39]


# Task 11

In [12]:
pixels = np.random.randint(0, 256, (5, 5))
print("Pixel Array:")
print(pixels)
print("Brightest Pixel:", np.max(pixels))
print("Darkest Pixel:", np.min(pixels))
print("Shape of Image:", pixels.shape)
print("\nAI reads images as arrays of pixel values.")

Pixel Array:
[[146 153 107 136   3]
 [211  50 136 244  22]
 [154 251 122 184 151]
 [177 121 255 133 227]
 [254  56  62 122  13]]
Brightest Pixel: 255
Darkest Pixel: 3
Shape of Image: (5, 5)

AI reads images as arrays of pixel values.


# Task 12

In [13]:
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Original Data:", data)
print("Normalized Data:", normalized)
print("\nNormalization improves AI performance")
print("by scaling data into a common range.")

Original Data: [10 20 30 40 50]
Normalized Data: [0.   0.25 0.5  0.75 1.  ]

Normalization improves AI performance
by scaling data into a common range.


# Task 13

In [14]:
dataset = np.array([
    [25, 50000, 1],
    [30, 60000, 0],
    [22, 45000, 1],
    [35, 80000, 0],
    [28, 70000, 1]
])
print("Dataset:")
print(dataset)
# Input features
X = dataset[:, :2]
# Output labels
y = dataset[:, 2]
print("\nInput Features:")
print(X)
print("\nOutput Labels:")
print(y)
print("\nAverage Salary:", np.mean(dataset[:, 1]))
print("Highest Age:", np.max(dataset[:, 0]))
print("Dataset Shape:", dataset.shape)

Dataset:
[[   25 50000     1]
 [   30 60000     0]
 [   22 45000     1]
 [   35 80000     0]
 [   28 70000     1]]

Input Features:
[[   25 50000]
 [   30 60000]
 [   22 45000]
 [   35 80000]
 [   28 70000]]

Output Labels:
[1 0 1 0 1]

Average Salary: 61000.0
Highest Age: 35
Dataset Shape: (5, 3)
