# NumPy for AI - Mini Project Assignment

## Create Dataset

In [1]:
import numpy as np
X = np.array([
    [78, 85, 80, 90],
    [45, 50, 40, 55],
    [88, 92, 85, 91],
    [60, 65, 70, 72],
    [35, 40, 38, 45],
    [95, 90, 93, 97],
    [55, 58, 60, 62],
    [82, 79, 88, 84],
    [48, 52, 46, 50],
    [73, 75, 78, 80]
])

## Separate Features

In [2]:
# Result labels
# 1 = Pass
# 0 = Fail
y = np.array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1])
print("Dataset:\n")
print(X)
print("\nLabels (Results):")
print(y)

Dataset:

[[78 85 80 90]
 [45 50 40 55]
 [88 92 85 91]
 [60 65 70 72]
 [35 40 38 45]
 [95 90 93 97]
 [55 58 60 62]
 [82 79 88 84]
 [48 52 46 50]
 [73 75 78 80]]

Labels (Results):
[1 0 1 1 0 1 1 1 0 1]


##  Calculate average, maximum, and minimum marks.

In [3]:
print("\n----- Statistics -----")
average_marks = np.mean(X)
maximum_marks = np.max(X)
minimum_marks = np.min(X)
print("Average Marks:", average_marks)
print("Maximum Marks:", maximum_marks)
print("Minimum Marks:", minimum_marks)


----- Statistics -----
Average Marks: 68.725
Maximum Marks: 97
Minimum Marks: 35


## Passed & Failed Students

In [4]:
passed_students = np.sum(y == 1)
failed_students = np.sum(y == 0)
print("\nPassed Students:", passed_students)
print("Failed Students:", failed_students)


Passed Students: 7
Failed Students: 3


## Students Scoring Above 80 and Below 50

In [5]:
print("\n----- Students Scoring Above 80 -----")
above_80 = X[X > 80]
print(above_80)
print("\n----- Students Scoring Below 50 -----")
below_50 = X[X < 50]
print(below_50)


----- Students Scoring Above 80 -----
[85 90 88 92 85 91 95 90 93 97 82 88 84]

----- Students Scoring Below 50 -----
[45 40 35 40 38 45 48 46]


##  Normalize Dataset

In [6]:
X_normalized = (X - np.min(X)) / (np.max(X) - np.min(X))
print("\n----- Normalized Dataset -----")
print(X_normalized)


----- Normalized Dataset -----
[[0.69354839 0.80645161 0.72580645 0.88709677]
 [0.16129032 0.24193548 0.08064516 0.32258065]
 [0.85483871 0.91935484 0.80645161 0.90322581]
 [0.40322581 0.48387097 0.56451613 0.59677419]
 [0.         0.08064516 0.0483871  0.16129032]
 [0.96774194 0.88709677 0.93548387 1.        ]
 [0.32258065 0.37096774 0.40322581 0.43548387]
 [0.75806452 0.70967742 0.85483871 0.79032258]
 [0.20967742 0.27419355 0.17741935 0.24193548]
 [0.61290323 0.64516129 0.69354839 0.72580645]]


## Simple Prediction Logic

In [7]:
student_average = np.mean(X, axis=1)
predictions = np.where(student_average >= 60, 1, 0)
print("\nPredicted Results:")
print(predictions)


Predicted Results:
[1 0 1 1 0 1 0 1 0 1]


## Calculate Accuracy

In [8]:
accuracy = np.mean(predictions == y) * 100
print("\nAccuracy of Predictions:", accuracy, "%")


Accuracy of Predictions: 90.0 %
